### ISSUE TITLE
Invitation: fix bugs

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/colab#126]
- [ ] Bug quand invite qqun. Not token found.
=> voir si se produit sans raison
=> revoir message d'erreur

- [x] Revoir l'interface sign in/sign up

**Comment by SandraMonnier** [comment]
- Bug quand delete un member: page blanche et Error: failure et infinite loading 
=> créé #265

**Comment by SandraMonnier** [comment]
Bug quand invite qqun traité dans #210
