### ISSUE TITLE
quand on crée quelque chose, entrer directement dedans en mode édition.

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/colab#154]
A faire pour projet, ressource, blocks.
Ne pas faire pour carte car peut vouloir en créer plusieurs de suite sans besoin d'édition entre deux

- [x] projet
- [x] card type
- card : do not do
- [x] resource
- [x] bloc : encore idéalement mettre le focus du curseur

**Comment by SandraMonnier** [comment]
Pour les documents / blocs, un début de solution à été mis en place (commit 9011f21395334de64dca2d1e755ea70efaf5c6f2)

**Comment by SandraMonnier** [comment]
- [ ] projet
- [ ] card type : do ?
- card : not do
- [ ] resource
- [ ] bloc : encore idéalement mettre le focus du curseur
