### ISSUE TITLE
Mettre message d’avertissement lors de rétrgradation de soi-même (droits)

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/colab#164]
- [x] Message avertissement lors de rétrogradation PAS SI SIMPLE!!
- [x] Impossible de s'enlever 'admin' si pas un 2ème admin
- [x] Impossible de se supprimer soi-même

**Comment by SandraMonnier** [comment]
Afficher adresse mail quand uniquement username -> pas de mail dans user? 
=> créé 286. à faire indépendamment
