### ISSUE TITLE
Ouvrir les projets dans un nouvel onglet

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/colab#178]

**Comment by audreyhuguenin** [comment]
- [ ]  Changer le Routing dans MainApp
- [ ] Open in new tab dans ProjectDisplay
- [ ] Adapter la vue Editor à un plein écran
- [ ] Ajouter un composant de navigation pour le retour aux projets dans Editor
- [ ] Changer le titre des tabs (actuellement "co.LAB" pour tous, ajouter - projects ou - nomDuProjet)

**Comment by SandraMonnier** [comment]
Le titre des tabs est changé. Voir avec un expert React si fait de manière trop naïve
