### ISSUE TITLE
info de où vient une ressource / un modèle de carte

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#190]

**Comment by audreyhuguenin** [comment]
**Ressources**: 
Fait par Sandra sur branche ressources.
A faire: réfléchir sur UX/UI

**CardTypes:**
fait par Sandra
A faire: unformier les icon entre ressource/cardTypes

**Comment by audreyhuguenin** [comment]
Uniformiser icons
Revoir en meme temps icons dans ressources
Bug toolbar dans ressources disparu
