### ISSUE TITLE
consolider le login.

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/colab#210]
Fonctionnel
- #278
- affichage statut connexion sur tous les onglets
=> #246 
- LoaderButton tourne si on fait la combinaison fausse
=> #266
- assert that a user can be only once in a project
=> #172 
- compter les tentatives d'après l'identifiant et non seulement s'il y a un account
=> #272
- onEnter ne fonctionne que la 2ème fois. Click OK.
=> Problème dans le formulaire. #259
- vérifier routage
=> #253 
- déconnexion disponible depuis tous les onglets
=> #244 
- sign up : ne pas laisser le navigateur préremplir les champs
=> #270
- [x] message "authentification failed" mais entre quand même dans le projet
=> voir si se reproduit depuis suppression de la double gestion du "Enter"
- [x] changer message d'info pour Forgot password
- messages informatifs pour le sign up
=> #102 

Design
- #275
- #277
- #274
- #276
- supprimer gros info "Some Data Are Missing"
=> #262
- [x] mettre toujours un texte pour les password feedback display afin que le ? n'apparaisse jamais seul. Pour reproduire : mettre "chattt" comme mot de passe dans le sign up.

**Comment by SandraMonnier** [comment]
close this issue, as all remaining points are issues
