### ISSUE TITLE
Validation of email for forgot password form

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/colab#236]
The idea is to check that the email address is really related to a user.

See if it triggers security flaw.

**Comment by SandraMonnier** [comment]
Décision 04.07.2022
Lors de la saisie d'une adresse mail pour changer son mot de passe, il n'est pas possible d'indiquer que le mot de passe ne correspond à aucun account de co.LAB. C'est une faille de sécurité.
Le fonctionnement doit être le suivant : 
- aucun feedback à propos de l'adresse mail
- si l'adresse mail ne correspond à aucun account, on n'envoie rien
- si l'adresse mail correspond à un account, on envoie un mail pour changer le mot de passe
