### ISSUE TITLE
simplifier pop up creation carte: enlever new type

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#26]

**Comment by SandraMonnier** [comment]
proposition : mettre dans l'écran de création de carte, un lien sur l'édition des modèles

**Comment by audreyhuguenin** [comment]
Bouton de renvoi à la page d'édition des modèles implémenté dans commit [cc1f4f0](https://github.com/Heigvd/colab/commit/cc1f4f03080cbcfaf2ad25c1b0fe6a83503ffa32)
