### ISSUE TITLE
Loader button : pouvoir le faire arrêter de tourner

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#266]
notamment lorsque l'action souhaitée est terminée (avec ou sans erreur)

**Comment by audreyhuguenin** [comment]
- Login
- Create password
- Invitation
- Create project
- Form
- Delete project
- Add card
- Add resource
- Delete Member
- Delet card or variant
- Delete cardType
- Create card type
- User profile edition
- ....
