### ISSUE TITLE
voir comment afficher info quand sign in / sign up fails

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#275]
Dans les pages de sign in, sign up, faire en sorte qu'un message d'erreur style "authentification failed" ou "choose another identifier" ne donne pas envie de pleurer ou de fuir

**Comment by audreyhuguenin** [comment]
Message above the form created.
Cannot make the catch after dispatch work + notification to delete in case of fail authentication comes from server.

**Comment by SandraMonnier** [comment]
Solution propre transmise par Maxence. 

Il reste à : 
- [ ] changer le message d'exception transmis par le SignIn
- [ ] faire un prettyPrint harmonisé dans Notifier
