### ISSUE TITLE
revoir message d'erreur "No token found"

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#278]
Pensez les messages d'erreurs de token (qui sont très technique) du point de vue de l'utilisateur qui va les recevoir. A discuter en vrai : Audrey + Sandra

**Comment by audreyhuguenin** [comment]
Propositions made for messages.
Check the process of invitations again: 
- bugs found:  invitation in spam box. 
- Check the redirections from Token.tsx

**Comment by SandraMonnier** [comment]
last fixes in commit c979069bd5cea766eba8cec05614d31f9b129796
