### ISSUE TITLE
Revoir structure de la toolbox dans card edition

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/colab#302]
Séparer barres d’outils:
gestion de la carte, 
gestion éléments de la carte
mise en forme du texte

+ toggle toolbox à revoir l'UX

**Comment by SandraMonnier** [comment]
Ancienne issue :

la barre (toolbox) d'édition de block contient en fait trois parties :

1. actions sur le livrable en entier (ajout de block)
2. actions de mise en forme du texte
3. actions sur le block (suppression, déplacement)

Proposition de mettre les actions concernant un block tout à droite.
Voir si autres changements

**Comment by SandraMonnier** [comment]
Ceci est caduc avec la mise en place du nouvel éditeur de texte Lexical
