### ISSUE TITLE
tip overflow

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#310]
please help me

![Screenshot 2022-08-16 at 18 35 16](https://user-images.githubusercontent.com/70577952/184932248-9cdedff0-9992-484a-af3a-e4dd4d88cac5.png)

**Comment by IamFonky** [comment]
![css-is-awesome-20090407-142244](https://user-images.githubusercontent.com/25899984/184932761-98be5a41-9763-40bc-8ec4-e4f7d354da25.jpg)

J'étais obligé désolé 😋
