### ISSUE TITLE
largeur livrable / documentation

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#321]
### Double click bloque la largeur de la documentation

Si on fait un double click dans un champ texte côté “documentation” (pour sélectionner un mot),  ça change la largeur de la colonne documentation (pas vraiment ce qu’on attendait) et on n’arrive ensuite plus à modifier la largeur de la colonne documentation.

=> à cause de la toolbar ?
=> si pas assez de place pour le livrable, ne pas avoir de scroll bar, mettre le texte en moins large. Et mettre … pour la toolbar

voir [22-09 Tests Dom](https://docs.google.com/document/d/1OFpjdQq632T5PlqKr4f-Hz96BQMBwbq6sEk1GoKCX54)

**Comment by audreyhuguenin** [comment]
Done in branch diverse-fixes

Scrollbars in both panels in case content does not fit. 
Open another issue for dev system to avoid scrollbars when too small?

**Comment by audreyhuguenin** [comment]
Fixed partly (what's needed for this milestone) in branch diverse-fixes

See #406 for what is left (avoiding scrollbars)
