### ISSUE TITLE
Barre "titre du model de design" apparait dans la carte

### ISSUE THREAD

**Issue by djaccard** [Heigvd/colab#337]

**Comment by maxencelaurent** [comment]
xenomicron inocorembus

**Comment by djaccard** [comment]
Fait un copié collé entre deux champs textes. La barres "serious games design" est apparue dans la carte.

<img width="1560" alt="Capture d’écran 2022-09-05 à 15 16 27" src="https://user-images.githubusercontent.com/1556490/188458577-83849bf3-fb3a-4093-9f39-28316904bd10.png">

**Comment by maxencelaurent** [comment]
c'est encore l'ancienne version du copier-coller qui est en ligne

**Comment by djaccard** [comment]
j'ai vu ;-)
aussi pour la navigation.

tu mets quand en ligne la nouvelle version ?

Le 5 sept. 2022 à 15:37, maxencelaurent ***@***.******@***.***>> a écrit :



c'est encore l'ancienne version du copier-coller qui est en ligne
