### ISSUE TITLE
upload files : reste bloqué

### ISSUE THREAD

**Issue by djaccard** [Heigvd/colab#345]
j'ai glissé déposé un fichier et ça reste bloqué dans cet état.
Rafraichissement de la page => OK le fichier a été uploadé.

<img width="988" alt="Capture d’écran 2022-09-08 à 09 10 31" src="https://user-images.githubusercontent.com/1556490/189058202-a3deecb3-a8b1-40b1-8ab3-b1fbf7d77ac0.png">

**Comment by SandraMonnier** [comment]
Dans React, l'adresse du fichier n'a pas changé. Le contenu derrière cette adresse fixe a lui changé. 
Comment forcer le re rendering de <img [...] src={currentPreviewImgUrl}/> dans FilePicker ?

**Comment by SandraMonnier** [comment]
Maxence :
En fait c'est le navigateur qui ne re render pas l'img vu que la src n'a pas changé.

Solution : mettre une query string genre &t=_modificationdate_ afin qu'il le re render

**Comment by SandraMonnier** [comment]
fixed by commit #bc14786f7e6e1e65d971bd5d1d67332bea8c738e
