### ISSUE TITLE
Navigation dans les cartes: back avec flèche envoye pas au bon endroit

### ISSUE THREAD

**Issue by djaccard** [Heigvd/colab#374]
Depuis la cart learning assessment, quand on clique sur la flèche pour remonter au niveau Assessment, on obtient:
<img width="1327" alt="Capture d’écran 2022-09-16 à 09 13 00" src="https://user-images.githubusercontent.com/1556490/190578912-828e119d-cf2b-489e-b638-21c25fa94522.png">

Au lieu de (i.e. ce qu'on obtient en cliquant sur le niveau "Assessment"):
<img width="1326" alt="Capture d’écran 2022-09-16 à 09 13 06" src="https://user-images.githubusercontent.com/1556490/190579017-56c8a406-a8d1-42be-ba56-be5b759f7843.png">

**Comment by SandraMonnier** [comment]
Pour le moment, la solution est de supprimer la flèche. Tout est possible de faire sans elle.
Voir une autre issue pour faciliter la navigation

**Comment by audreyhuguenin** [comment]
Done in branch diverse-fixes
