### ISSUE TITLE
Brainstormer tous les modèles

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#382]
- modèle de projet
- modèle de carte
- documentation venue d'ailleurs

Première approche pour proposer une solution générale pour la lecture, l'édition et la publication des modèles

**Comment by audreyhuguenin** [comment]
Discussion du 27.09.22
Voir PV [(https://docs.google.com/document/d/1RNyFeQ3sGWkf82DStb-TELQN4PmUleyExswaAlvIJD8/edit)]
