### ISSUE TITLE
Rendre disponible en 1 clic l'édition d'un lien

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#387]
On veut éditer un bloc lien. Si on clique sur le crayon dans le bloc, on n'arrive pas à l'édition du lien directement. Il faut cliquer une deuxième fois.

**Comment by TehAwol** [comment]
L'erreur provient de DocumentEditor.tsx à la ligne 63. Le useCallback se déclenche après le onClick de OpenGraphLink.tsx et est donc annuler au premier click,

**Comment by SandraMonnier** [comment]
caduc avec la mise en place du nouvel éditeur de texte Lexical
