### ISSUE TITLE
Revoir UX d’ajout des différents blocs

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#44]
Barre d'outils unique pour toute la carte

**Comment by audreyhuguenin** [comment]
- Fixed header de carte
- Barre d'outils fixe (toujours même hauteur?), bouton pour la masquer (collapse)
- Contenu: 
- (always) boutons d'ajout de bloc, delete bloc, edit bloc 
- (contextual) Texte: option de formatage de texte, Lien: refresh, File: nothing (yet)
