### ISSUE TITLE
Effacer un projet ouvert provoque un chargement infini

### ISSUE THREAD

**Issue by TehAwol** [Heigvd/colab#473]
### Reproduction
- Ouvrir un project (dans un nouvel onglet)
- Effacer le project ouvert depuis l'accueil
- Quand on revient sur l'onglet du project, il charge infiniment

**Comment by SandraMonnier** [comment]
fixed by commit 550f4ce4bfec47b6dce742f934b958049fa33438

**Comment by SandraMonnier** [comment]
Quand le client reçoit "null" au lieu d'un projet, il met un statut d'erreur dans le store
