### ISSUE TITLE
Message d'erreur après suppression d'une carte

### ISSUE THREAD

**Issue by djaccard** [Heigvd/colab#490]
<img width="794" alt="Capture d’écran 2023-03-23 à 08 53 55" src="https://user-images.githubusercontent.com/1556490/227138451-c4470133-c81f-4b9d-9fec-ee1f47e37ff4.png">

**Comment by SandraMonnier** [comment]
A partir de ce moment, l'application est dans un état instable. Il faut la redéployer.

**Comment by SandraMonnier** [comment]
s'est reproduit 
[colab-prod-payara-5f95d5dc6b-rhcjc_colab-prod-payara.log](https://github.com/Heigvd/colab/files/11139649/colab-prod-payara-5f95d5dc6b-rhcjc_colab-prod-payara.log)
