### ISSUE TITLE
Message erreur après redimensionnement d'une carte

### ISSUE THREAD

**Issue by djaccard** [Heigvd/colab#491]
<img width="990" alt="Capture d’écran 2023-03-23 à 08 56 15" src="https://user-images.githubusercontent.com/1556490/227138962-0a969eb6-731c-4e8b-8ff1-6d2bf867d813.png">

**Comment by SandraMonnier** [comment]
Doublon. La suite de #490. L'état est instable pour toute action sur la DB.
