### ISSUE TITLE
Ressource settings

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#50]

**Comment by SandraMonnier** [comment]
Le gros est traité. Reste à finaliser

**Comment by SandraMonnier** [comment]
reste à faire : 
- [ ] pouvoir mettre un slash
- [ ] pouvoir supprimer la catégorie
- [ ] changer la catégorie pour toutes les ressources dessous

**Comment by maxencelaurent** [comment]
```
@Path("patatiPatata/{category : .*)
```
