### ISSUE TITLE
pouvoir positionner les blocs - côté serveur

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#58]
permettre de définir où l'on veut insérer un bloc

**Comment by SandraMonnier** [comment]
cas de figure :
1. on veut monter un bloc
2. on veut descendre un bloc
3. on veut mettre un bloc avant les blocs existants
4. on veut mettre un bloc entre deux blocs existants
5. on veut mettre un bloc après les blocs existants

**Comment by SandraMonnier** [comment]
méthodes REST prévues :
* moveDocUp(docId)
* moveDocDown(docId)
* moveDocAfter(docId, previousId)
* moveDocBefore(docId, nextId)
* moveDocAtBottom(docId)

@audreyhuguenin est-ce que cela te convient ?

**Comment by audreyhuguenin** [comment]
Oui, c'est top. Merci beaucoup!

**Comment by SandraMonnier** [comment]
fixed by commit c7970d9f1031168d68b4260197680f95910d4b39
