### ISSUE TITLE
pouvoir créer un projet à partir d'un autre

### ISSUE THREAD

**Issue by SandraMonnier** [Heigvd/colab#64]

**Comment by audreyhuguenin** [comment]
- UX: Maquettes à discuter
- SERVER: in progress

**Comment by SandraMonnier** [comment]
- SERVER : la duplication d'un projet est en place. Tout est copié sauf les membres de l'équipe. Les modèles de carte ne sont pas copiées, mais référencées par le nouveau projet (ainsi toute modification faite dans un type sera transmise). Il manque la copie des sticky notes et des activity flow.
- CLIENT : les maquettes sont implémentées de manière purement fonctionnelle, sans aucun effort de style

**Comment by SandraMonnier** [comment]
SERVER : il manque encore la copie d'un document uploadé

entrer automatiquement dans le projet, dès que créé

**Comment by SandraMonnier** [comment]
commit b603467388e6a135b00d2d0a72d02dcffbac9aa5 par Audrey pour l' UI
