### ISSUE TITLE
Dissocier composant BlockEditorWrapper et un autre pour edition de stickyNote explanation, resource teaser et cardType purpose

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/colab#65]
Pouvoir utiliser le composant BlockEditorWrapper uniquement pour les blocks de cartes et des ressources.

Si on veut des text styling features, réfléchir à un autre composant que BlockEditorWrapper pour 
- stickyNote explanation
- resource teaser
- cardType purpose
car pas besoin de liveEditing (?)

Un plus: Pouvoir accéder directement à la valeur (string) de ces éléments et non uniquement à leur id dans les fichiers correspondants: 
- StickyNoteDisplay.tsx: stickyNote.explanation (actuellement accès à stickyNote.explanationId)
- ResourceMiniDisplay.tsx: targetResource.teaser (actuellement accès à targetResource.teaserId)
- CardTypeEditor.tsx: cardType.purpose (actuellement accès à targetResource.cardType.purposeId)

**Comment by SandraMonnier** [comment]
Ajout de 
- useAndLoadTextOfDocument 
- DocTextDisplay
pour une utilisation simple de text data block

fixed in commit 0096107c7ef303217d352032402cacf2af0caff0

**Comment by SandraMonnier** [comment]
Audrey a créé DocTextWrapper pour l'édition de text data block
