### ISSUE TITLE
Création de ressource: checkbox "Is only for present version" à expliciter

### ISSUE THREAD

**Issue by audreyhuguenin** [Heigvd/colab#82]
- Ne pas mettre dans le card type editor
- Seulement quand il y a plusieurs variantes
- Changer le label pour plus explicite

**Comment by SandraMonnier** [comment]
la checkbox ne sera mise que dans le cas où il y a plusieurs variantes.

Pour le moment, le label n'est pas modifié

**Comment by SandraMonnier** [comment]
commit 42d15782b46616e859c7e38bf57257217ec1c6d5
